### ISSUE TITLE
top and bottom corners cut off

### ISSUE THREAD

**Issue by jorvlan** [GuangchuangYu/hexSticker#125]
Hi,

I wanted to ask how I can prevent that the top and bottom points are being removed from the `ggplot2` `sticker` function?
I read one of the earlier issues here, in which you suggested to install version 0.4.4, but since the current version is 0.4.9, I don't think that will resolve my issue? 

The code I am using to produce the sticker:
```r
s <- sticker(raincloud_3, package="Raincloudplots", p_size=5.5, s_x=1, s_y=.8, s_width=1.6, s_height = .8, h_fill="#F6FFFF", h_size = 2.5, h_color="darkorange", p_color = "dodgerblue",
             filename="/Users/jordyvanlangen/Desktop/rainclouds_highres.png", dpi = 900)
s
```
Many thanks

**Comment by jorvlan** [comment]
Sorry, I thought it was due to my computer, but the `white_around_sticker` option resolved it.

**Comment by duckmayr** [comment]
I think it would be nice to address this actually, since it requires the user to choose between having white around the sticker (which they may not want) or having the top and bottom corners cut off; it would be good to be able to have the top and bottom corners as well as have transparency around the sticker.
