### ISSUE TITLE
Select font typeface

### ISSUE THREAD

**Issue by jotsetung** [GuangchuangYu/hexSticker#4]
Would be nice if it was not only possible to select the font family (`p_family`) but also the font typeface (e.g. `Lt`, `Rg`) etc. or directly select the font e.g. `p_font = "Aller_Lt"`.

**Comment by GuangchuangYu** [comment]
new `p_family` supports passing value like `Aller_Rg`, `Aller_Lt` etc.

I would like to keep using `p_family` instead of `p_font` and the `p_family` is to specific `family` passing to `geom_text` or `annotate("text",...)` and it work exactly the same way in addition of internally support `Aller`.

If user want to use specific fonts (e.g. google font), they can use `showtext` to load the font manually and also pass to the `p_family` parameter.

I like this way to keep minimal and consistent parameters without scaring people.

**Comment by henningsway** [comment]
How can I easily see, which fonts are available? Are fonts from the `extrafont`-package supposed to work?

**Comment by GuangchuangYu** [comment]
`hexSticker` internally use `showtext` and current implementation doesn't support `extrafont`.
